# Generated by Django 6.0.2 on 2026-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
