# Generated by Django 6.0.2 on 2026-02-17 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_value', models.FloatField(blank=True, null=True)),
                ('new_value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
