# Generated by Django 6.0.2 on 2026-03-01 08:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique code identifying the event, e.g., 'kpi_assigned'", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for the event', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the event', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Flag to enable/disable this event type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the event type was last updated')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'db_table': 'event_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(default='This is the transaction history of this event', help_text='Human-readable description of what happened')),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_uuid', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.ForeignKey(blank=True, help_text='The type of event that triggered this log entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_logs', to='Transaction.eventtypes')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Base.status')),
            ],
            options={
                'db_table': 'transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
