# Generated by Django 6.0.2 on 2026-02-17 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('kpis', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('underperformance', 'Underperformance'), ('excellent', 'Excellent Performance'), ('Average performance', 'Average Performance'), ('Improved performance', 'Improved Performance')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('kpi_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kpis.kpiassignment')),
                ('notified_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_kpi_alerts', to='organization.department')),
                ('notified_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_alerts', to='accounts.role')),
                ('notified_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_kpi_alerts', to='organization.team')),
                ('notified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_kpi_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_result', to='organization.department')),
                ('team_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_result', to='organization.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_summaries',
            },
        ),
    ]
