# Generated by Django 6.0.2 on 2026-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesummary',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
