# Generated by Django 6.0.2 on 2026-03-01 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        ('accounts', '0001_initial'),
        ('kpis', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('underperformance', 'Underperformance'), ('excellent', 'Excellent Performance'), ('Average performance', 'Average Performance'), ('Improved performance', 'Improved Performance')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('kpi_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kpis.kpiassignment')),
                ('notified_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_kpi_alerts', to='organization.department')),
                ('notified_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_alerts', to='accounts.role')),
                ('notified_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_kpi_alerts', to='organization.team')),
                ('notified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_kpi_alerts', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.status')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('summary_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('department', 'Department')], default='individual', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='organization.department')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.status')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_summaries', to='organization.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_summaries',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('kpi_alert', 'KPI Alert'), ('summary', 'Performance Summary')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='performance.kpialert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='performance.performancesummary')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancesummary',
            constraint=models.UniqueConstraint(condition=models.Q(('summary_type', 'individual')), fields=('user', 'period_start', 'period_end'), name='unique_individual_summary'),
        ),
        migrations.AddConstraint(
            model_name='performancesummary',
            constraint=models.UniqueConstraint(condition=models.Q(('summary_type', 'team')), fields=('team', 'period_start', 'period_end'), name='unique_team_summary'),
        ),
        migrations.AddConstraint(
            model_name='performancesummary',
            constraint=models.UniqueConstraint(condition=models.Q(('summary_type', 'department')), fields=('department', 'period_start', 'period_end'), name='unique_department_summary'),
        ),
    ]
