# Generated by Django 6.0.2 on 2026-03-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
        ('kpis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiresults',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kpiresults',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiresults',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kpi_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='kpiresults',
            constraint=models.UniqueConstraint(fields=('submitted_by', 'kpi_assignment'), name='unique_submitted_by_kpi_assignment'),
        ),
    ]
