# Generated by Django 6.0.2 on 2026-03-16 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_kpiresults_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidefinition',
            name='weight_value',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Weight between 1 and 10', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
