# Generated by Django 6.0.2 on 2026-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_alter_kpidefinition_weight_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiformula',
            name='formula_template',
            field=models.CharField(blank=True, choices=[('higher', 'Higher is Better'), ('lower', 'Lower is Better'), ('task', 'Task Completion'), ('progress', 'Progress Above Minimum'), ('custom', 'Advanced Custom Formula')], max_length=20, null=True),
        ),
    ]
