# Generated by Django 6.0.2 on 2026-03-01 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kpi_name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('quarterly', 'QUARTERLY'), ('yearly', 'YEARLY')], default='monthly', max_length=20)),
                ('kpi_description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('measurement_type', models.CharField(help_text='% ,hours, number', max_length=50)),
                ('min_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiAssignment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_start', models.DateField(blank=True, help_text='Start date', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date', null=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignments', to='organization.department')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignments', to='organization.team')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assignments', to='Base.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpis.kpidefinition')),
            ],
            options={
                'db_table': 'kpisAssignments',
            },
        ),
        migrations.CreateModel(
            name='KPIFormula',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('formula_name', models.CharField(blank=True, max_length=30, null=True)),
                ('period_start', models.DateField(blank=True, help_text='Start date', null=True)),
                ('formula_expression', models.TextField(help_text='Example: (actual / target) * 100')),
                ('data_source', models.CharField(blank=True, help_text='Example: manual_entry, jira_api,', max_length=100)),
                ('outstanding_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Score >= this = Outstanding. Default 90', max_digits=5, null=True)),
                ('good_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Score >= this = Good. Default 75', max_digits=5, null=True)),
                ('satisfactory_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Score >= this = Satisfactory. Default 60', max_digits=5, null=True)),
                ('needs_improvement_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Score >= this = Needs Improvement. Default 40', max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='kpis.kpidefinition')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpisFormula',
            },
        ),
        migrations.CreateModel(
            name='KPIResults',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10)),
                ('calculated_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rating', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kpi_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpis.kpiassignment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_kpi_results', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.status')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='The individual member submitting under a team/dept assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_kpi_results', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpisResults',
            },
        ),
    ]
